# Form implementation generated from reading ui file 'menu1.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 560)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"QPushButton {\n"
"    color: white ; \n"
"    background-color:rgb(0,0,0);\n"
"    border: 1px solid;\n"
"    border-color: #ffffff\n"
"}\n"
"QLabel {\n"
"    color: white ; \n"
"    background-color:rgb(0,0,0);\n"
"    border: 1px solid;\n"
"    border-color: #ffffff\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonEplayer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonEplayer.setGeometry(QtCore.QRect(260, 280, 141, 91))
        self.buttonEplayer.setObjectName("buttonEplayer")
        self.buttonNewP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonNewP.setGeometry(QtCore.QRect(440, 280, 141, 91))
        self.buttonNewP.setObjectName("buttonNewP")
        self.buttonGuest = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonGuest.setGeometry(QtCore.QRect(90, 280, 141, 91))
        self.buttonGuest.setObjectName("buttonGuest")
        self.notice1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.notice1.setGeometry(QtCore.QRect(80, 40, 551, 171))
        self.notice1.setObjectName("notice1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonEplayer.setText(_translate("MainWindow", "Existing Player"))
        self.buttonNewP.setText(_translate("MainWindow", "New Player"))
        self.buttonGuest.setText(_translate("MainWindow", "Guest"))
        self.notice1.setText(_translate("MainWindow", " To clarify your saved data for use, you can:\n"
" -Log in as a guest: your scores will not be saved and as a result, no skill calculations can be performed \n"
" -Log in as an existing player: If you have an existing player save \n"
" -Log in as a new player: If you do not have an existing player save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
